// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCopyrightAttribute("Copyright ©2013-2017 ICT Baden GmbH")]
[assembly: AssemblyCompanyAttribute("ICT Baden GmbH")]
[assembly: AssemblyProductAttribute("Web Application Framework")]
[assembly: AssemblyVersionAttribute("2.1.3")]
[assembly: AssemblyFileVersionAttribute("2.1.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyCopyright = "Copyright ©2013-2017 ICT Baden GmbH";
        internal const System.String AssemblyCompany = "ICT Baden GmbH";
        internal const System.String AssemblyProduct = "Web Application Framework";
        internal const System.String AssemblyVersion = "2.1.3";
        internal const System.String AssemblyFileVersion = "2.1.3";
    }
}
